version: '3.9'

services:
  openhands:
    build:
      context: ./ 
      dockerfile: ./containers/app/Dockerfile
    image: openhands:latest
    container_name: openhands-app
    environment:
      - SANDBOX_RUNTIME_CONTAINER_IMAGE=docker.all-hands.dev/all-hands-ai/runtime:0.42-nikolaik
      - WORKSPACE_MOUNT_PATH=${WORKSPACE_BASE:-$PWD/workspace}
      - SANDBOX_VSCODE_PORT=41234
      - ENABLE_VSCODE=true

    ports:
      - "3000:3000"
      - "41234:41234"  # fixed VS Code port
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.openhands-state:/.openhands-state
      - ${WORKSPACE_BASE:-$PWD/workspace}:/opt/workspace_base
    pull_policy: build
    stdin_open: true
    tty: true

